spring.application.name=logshield-v2

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.packages-to-scan=com.logshield.logshieldv2.controller
springdoc.paths-to-match=/api/v1/**
